- project:
    check:
      jobs:
        # TripleO jobs that deploy networking-bgpvpn.
        # Note we don't use a project-template here, so it's easier
        # to disable voting on one specific job if things go wrong.
        # tripleo-ci-centos-7-scenario004-multinode-oooq will only
        # run on stable/pike while the -container will run in Queens
        # and beyond.
        # If you need any support to debug these jobs in case of
        # failures, please reach us on #tripleo IRC channel.
        - tripleo-ci-centos-7-scenario004-multinode-oooq:
            voting: false
        - tripleo-ci-centos-7-scenario004-multinode-oooq-container:
            voting: false
        - openstack-tox-pep8:
            required-projects: openstack/networking-odl
        - openstack-tox-py27:
            required-projects: openstack/networking-odl
        - openstack-tox-py35:
            required-projects: openstack/networking-odl
        - build-openstack-sphinx-docs:
            required-projects: openstack/networking-odl
        - openstack-tox-cover:
            required-projects: openstack/networking-odl
    gate:
      jobs:
        - openstack-tox-pep8:
            required-projects: openstack/networking-odl
        - openstack-tox-py27:
            required-projects: openstack/networking-odl
        - openstack-tox-py35:
            required-projects: openstack/networking-odl
        - build-openstack-sphinx-docs:
            required-projects: openstack/networking-odl
        - openstack-tox-cover:
            required-projects: openstack/networking-odl
    periodic-stable:
      jobs:
        - build-openstack-sphinx-docs:
            required-projects: openstack/networking-odl
        - openstack-tox-py27:
            required-projects: openstack/networking-odl
