- project:
    templates:
      - openstack-python-jobs-neutron
      - openstack-python35-jobs-neutron
      - openstack-python36-jobs-neutron
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
      - periodic-stable-jobs-neutron
      - check-requirements
    check:
      jobs:
        # TripleO jobs that deploy networking-bgpvpn.
        # Note we don't use a project-template here, so it's easier
        # to disable voting on one specific job if things go wrong.
        # tripleo-ci-centos-7-scenario004-multinode-oooq will only
        # run on stable/pike while the -container will run in Queens
        # and beyond.
        # If you need any support to debug these jobs in case of
        # failures, please reach us on #tripleo IRC channel.
        - tripleo-ci-centos-7-scenario004-multinode-oooq:
            voting: false
        - tripleo-ci-centos-7-scenario004-multinode-oooq-container:
            voting: false
        - openstack-tox-lower-constraints:
            required-projects:
              - openstack/neutron
              - openstack/networking-bagpipe
              - openstack/horizon
        - horizon-openstack-tox-python3-django111
        - openstack-tox-pep8:
            required-projects:
              - openstack/networking-bagpipe
              - openstack/horizon
        - openstack-tox-py27:
            required-projects:
              - openstack/networking-bagpipe
              - openstack/horizon
        - openstack-tox-py35:
            required-projects:
              - openstack/networking-bagpipe
              - openstack/horizon
        - openstack-tox-py36:
            required-projects:
              - openstack/networking-bagpipe
              - openstack/horizon
        - legacy-tempest-dsvm-networking-bgpvpn-bagpipe:
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^setup.cfg$
        - openstack-tox-cover:
            required-projects:
              - openstack/neutron
              - openstack/networking-bagpipe
              - openstack/horizon
        - legacy-networking-bgpvpn-dsvm-functional
    gate:
      jobs:
        - openstack-tox-lower-constraints:
            required-projects:
              - openstack/neutron
              - openstack/networking-bagpipe
              - openstack/horizon
        - horizon-openstack-tox-python3-django111
        - openstack-tox-pep8:
            required-projects:
              - openstack/networking-bagpipe
              - openstack/horizon
        - openstack-tox-py27:
            required-projects:
              - openstack/networking-bagpipe
              - openstack/horizon
        - openstack-tox-py35:
            required-projects:
              - openstack/networking-bagpipe
              - openstack/horizon
        - openstack-tox-py36:
            required-projects:
              - openstack/networking-bagpipe
              - openstack/horizon
        - legacy-tempest-dsvm-networking-bgpvpn-bagpipe:
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^setup.cfg$
        - legacy-networking-bgpvpn-dsvm-functional
    experimental:
      jobs:
        - legacy-networking-bgpvpn-dsvm-install
        - legacy-networking-bgpvpn-bagpipe-dsvm-install
        - legacy-networking-bgpvpn-bagpipe-dsvm-functional
    post:
      jobs:
        - publish-openstack-python-branch-tarball:
            required-projects:
              - openstack/networking-bagpipe
              - openstack/horizon
